# Generated by Django 3.1.1 on 2020-09-19 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='acitve',
            field=models.BooleanField(default=True),
        ),
    ]
